name: Generate Report

on:
  schedule:
    - cron: '0 18 * * *' # run at 2am singapore time, change to '0 0 * * *' to run at 8am singapore time later
  push:
    branches: [ "actions/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Python script
      run: |
        python main.py ${{ secrets.WEBHOOK_URL }}
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
